### ISSUE TITLE
Vertically centering in the unknown with table-cell doesn't work

### ISSUE THREAD

**Issue by blmstr** [oliverzheng/howtocenterincss#17]
When I input unknown width and height for both container and content I get this output which doesn't center content vertically:
```html
<div style="display:table-cell;vertical-align:middle;">
  <div></div>
</div>
````

You need to have a wrapping element with display table like this: http://codepen.io/blmstr/pen/OVLarb

**Comment by oliverzheng** [comment]
Yeah this wasn't thoroughly tested. Gonna create some webdriver tests to go through all of them across browsers/platforms. Thanks for reporting!

**Comment by oliverzheng** [comment]
Actually, it should work, for px and em units.

The outer table wrapping is only necessary if percentage units are needed. This is because the table-cell element implicitly creates two hidden DOM elements around itself with display:table-row and display:table, unless there's an element around it already that has these display options. In the case of percentage heights, if the table-cell has 100% height, it's actually 100% of the height of the hidden table-row, which has a height as big as the content of the table-cell, effectively making this 100% useless. What's required is to have that wrapper table be 100% high, so the table-row and table-cell auto stretch to its height.

**Comment by blmstr** [comment]
@oliverzheng Not sure I'm following, do you have an example of that?

**Comment by oliverzheng** [comment]
@blmstr this works without needing a table to wrap around the table-cell: http://codepen.io/anon/pen/VLmyXp

**Comment by blmstr** [comment]
@oliverzheng I've never seen that before. That's great!

**Comment by oliverzheng** [comment]
7764f69 should have fixed this.
