### ISSUE TITLE
Disable Generate button until all inputs are filled in

### ISSUE THREAD

**Issue by manti** [oliverzheng/howtocenterincss#32]
Uncaught Error: Invariant Violation No content

**Comment by oliverzheng** [comment]
Did you select either text or div and fill in the options there?

**Comment by manti** [comment]
@oliverzheng yes

**Comment by oliverzheng** [comment]
@manti I can't repro. Can you take a screenshot of what you selected?

(This would be much easier once #6 is done.)

**Comment by htmlstream** [comment]
I've just wanted to confirm about the same issue. The live demo page http://howtocenterincss.com is not working either for text and div.

**Comment by oliverzheng** [comment]
@htmlstream can you paste a screenshot here of your browser? As well as what's in the console?

**Comment by halfarchange** [comment]
If you tick only a few choices but not all, the generate button does nothing not even display an error on Chrome/Win7 (latest).
If we inspect the console we see : 
bundle.min.js:3 Uncaught Error: Invariant Violation: No horizontal alignment

If we click on horizontal alignment but not the vertical alignment (to be honest I didnt see it the first time because it's on the right) same problem, the hidden console error message switch to the vertical one.

**Comment by oliverzheng** [comment]
Gotcha that makes sense. I'll look into adding some sensible error message.

**Comment by manti** [comment]
:+1:

**Comment by ArtskydJ** [comment]
@oliverzheng maybe instead of an error message, the generate button should just be grayed out until all the required options are filled out.

**Comment by oliverzheng** [comment]
Good idea. Perhaps show a tooltip to say why as well. Does someone want to put up a pull request? :)
