### ISSUE TITLE
Translation to portuguese

### ISSUE THREAD

**Issue by grvcoelho** [oliverzheng/howtocenterincss#37]
Would you mind if I fork it and create a portuguese version? :smile:

**Comment by oliverzheng** [comment]
Did you want to make a new site, or just have a language toggle on the page? I'd prefer the latter, since the algorithms/methods get updated and I'd rather keep a central location for that.

I know nothing about development in Portuguese. Do Portuguese speakers search for "center" in Portuguese? Most of the traffic of the site comes from search engines and referrals, and I'd imagine Portuguese speakers would get more out of the page being able to toggle the language.

**Comment by grvcoelho** [comment]
Yes, they do search a lot the terms in portuguese :D If you want, we could put the toggle on the page! No problem about that! But it would be nice to have a portuguese domain like www.comoalinharemcss.com to redirect :D

**Comment by oliverzheng** [comment]
Oh yeah sounds good. Feel free to submit a pull request for the toggle & buy the domain.

I haven't done any real i18n work, so feel free to use whatever you feel is reasonable.

**Comment by woliveiras** [comment]
Or it could be http://howtocenterincss.com/pt ;)

**Comment by oliverzheng** [comment]
Sure :)
