### ISSUE TITLE
Centering text vertically when height is 100%

### ISSUE THREAD

**Issue by FelisPhasma** [oliverzheng/howtocenterincss#41]
While trying to center text vertically when height of the parent is 100%, this code is generated:

`line-height: 100%;`

Unfortunately that sets the line height to 100% of the font size and not the parent. I propose the following change:

`line-height: 100vh;`

Which works in most modern browsers.
http://caniuse.com/#search=vh

**Comment by oliverzheng** [comment]
@FelisPhasma can you post the link after you click Generate Code? It'll include all the input options.

**Comment by FelisPhasma** [comment]
@oliverzheng Sure! [http://howtocenterincss.com/#contentType=text&content.text.lines=1&container.height=100pct&horizontal=left&vertical=middle&browser.IE=none](http://howtocenterincss.com/#contentType=text&content.text.lines=1&container.height=100pct&horizontal=left&vertical=middle&browser.IE=none)

**Comment by oliverzheng** [comment]
Ah I see the problem. Unfortunately, `vh` won't work for cases where the parent's 100% height isn't actually the viewport's height. `vh` is only the height of the viewport.

I imagine this might need to use the table cell approach. Absolute positioning won't work, since the height of the text is unknown because of the unknown font-size...
